### ISSUE TITLE
error invalid value for card

### ISSUE THREAD

**Issue by djbr1** [Rhizomatica/mercury#2]
Mercury was compiled, starts and throws error:
`
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
mercury: pcm.c:1259: snd_pcm_start: Assertion pcm failed.`

please advise how to determine correct card (OS Ubuntu) and where to change in source code.

73
hb9txb

**Comment by Fadijerji** [comment]
You can list all of your  output ALSA devices by running "aplay -L" and all of your  input ALSA devices by running "arecord -L"

Then adjust the device name in main.cc line 99 for play and line 282 for capture.

The current value is "plughw:1,0", most probably you would have only one sound card and the device name would be "plughw:0,0"

Fadi.

**Comment by Fadijerji** [comment]
Source code is updated and the config lines were moved to 92 and 93:

telecom_system.microphone.dev_name="plughw:0,0";
telecom_system.speaker.dev_name="plughw:0,0";

Fadi

**Comment by djbr1** [comment]
thanks, using latest commit with new default values (plughw:0,0) it works without modification

Please provide explanation of command line parameters used when starting mercury

**Comment by Fadijerji** [comment]
No command line parameters are needed to start mercury. The configuration is in the top of main.cc and explained in the Readme file.

I will close this issue to keep issue seperated by subject. Feel free to open a new issue for new jubjects.

Fadi
