### ISSUE TITLE
Version 0.2 exits immediately

### ISSUE THREAD

**Issue by rafael2k** [Rhizomatica/mercury#6]
Version 0.2 exits immediately.

This line seems suspicious to me:

https://github.com/Rhizomatica/mercury/blob/f213a0bc23063c5ed87c5e8eef5dbc7aec8ef7dc/source/datalink_layer/arq_common.cc#L467

**Comment by Fadijerji** [comment]
the code block was commented, it is meant to print a list of config bit rate and exit, not part of the operational code.
