### ISSUE TITLE
Connection failure between two sBitx on dummy load

### ISSUE THREAD

**Issue by rafael2k** [Rhizomatica/mercury#7]
I'm trying to run version 0.2 on a couple of sBitx on dummy loads, but it does not connect. Tried with both uucpd and mercury-connector as clients.

Is there any change needed in the code?

Could you share your RF test setup, so I can try to replicate here?

**Comment by Fadijerji** [comment]
using the configurations source/physical_layer/physical_config.cc and source/datalink_layer/datalink_config.cc the configuration can be alterd for each radio.
the physical layer can be tested on its own using TX_TEST and RX_TEST modes
Verify the power value (changed to 0.1 in Mercury V0.2 to avoid ALSA saturation and distortion)
"output_power_Watt=0.1;"

**Comment by rafael2k** [comment]
The "output_power_Watt" is just a multiplier to the signal sample, right?

**Comment by Fadijerji** [comment]
This controls the power of the output signal by multiplying the samples with the sqrt(output_power_Watt)

https://github.com/Rhizomatica/mercury/blob/d68ae7746d6affc69322f36f6dea5d5b7eb7828b/source/physical_layer/telecom_system.cc#L365

and

https://github.com/Rhizomatica/mercury/blob/d68ae7746d6affc69322f36f6dea5d5b7eb7828b/source/physical_layer/telecom_system.cc#L371

**Comment by rafael2k** [comment]
Thanks. With regards to the filters, they are set to the sbitx, just like in 0.1.5 right?
