### ISSUE TITLE
Gear-shift setup

### ISSUE THREAD

**Issue by rafael2k** [Rhizomatica/mercury#8]
I can see in datalink_config.cc the following:
```
gear_shift_on=NO;
```

Could you confirm version 0.2 has gear shift implemented?

**Comment by Fadijerji** [comment]
As mentioned in the read me, tow gear shift algorithms are implemented in Mercury 0.2.
you can switch the gear shift on by setting:

gear_shift_on=YES;

:)

**Comment by rafael2k** [comment]
Is there a reason why one should leave it off?

**Comment by Fadijerji** [comment]
This would be up to the user to activate it or not.
