### ISSUE TITLE
Possible divide by zero

### ISSUE THREAD

**Issue by srsampson** [Rhizomatica/mercury#9]
In ofdm.cc
https://github.com/Rhizomatica/mercury/blob/main/source/physical_layer/ofdm.cc#L377

The atan() function may get a ```mul.real()``` value of 0.0 which would return a Nan probably.

This should probably be replaced by the ```misc.cc``` get_angle(complex) algorithm. But that function also has a divide by zero possibility.

Change to:
```
double get_angle(std::complex <double> value)
{
	double theta=0;

        if(value.real() == 0) // check for divide by zero
        {
                theta = 0;
        }
	else if(value.real() >0)
	{
		theta=atan(value.imag()/value.real());
	}
	else if (value.real() <0 && value.imag() >=0)
	{
		theta=atan(value.imag()/value.real()) +  M_PI;
	}
	else if (value.real() <0 && value.imag() <0)
	{
		theta=atan(value.imag()/value.real()) -  M_PI;
	}

	return theta;
}
```

**Comment by rafael2k** [comment]
Thanks Steve. You are right, this is a possible issue. I'll commit the fix today.

**Comment by rafael2k** [comment]
Could you please take a look if there are no more divide by zero in OFDM code?
Here is the commit with your fix (and another divide by zero):
https://github.com/Rhizomatica/mercury/commit/60fada8593e40effe6d3d21b45cd9648ecdd116c

**Comment by srsampson** [comment]
This is the way I did it. Hopefully it's not completely wrong. I simplified the PI math.
```
        double frequency_offset_precision;

        if (mul.real() == 0) {
            frequency_offset_precision = 0;
        } else {
            // simplified math [ 2 * (1 / 2π)] = [1 / π]
            frequency_offset_precision = get_angle(mul) / Math.PI;
        }
```

**Comment by srsampson** [comment]
After thinking about it, the algorithm might be further simplified:
```
double frequency_offset_precision = get_angle(mul) / Math.PI;
```
Since get_angle() checks for divide by zero itself.

**Comment by rafael2k** [comment]
Indeed. Please double check if this is correct:
https://github.com/Rhizomatica/mercury/commit/3950761d5250e34f7db2e90f17c4cbe9ea0ee0bb

**Comment by srsampson** [comment]
If the real value is 0, then ```frequency_offset_prec``` will be: (M_PI / 2 * M_PI) or .5

**Comment by srsampson** [comment]
yes, thanks!

**Comment by rafael2k** [comment]
Thanks @srsampson!
